name: Generate GitHub Trophy

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  trophy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: hasan-imran-nazir
          output_path: ./trophy.svg

      - name: Push trophy to trophy-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: trophy-output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}